unique_ids:
  forms: {Switch: NWAC5LQIAS54YVF6LOV7HLT7GGF2IATJ, EditableCard: ZPZ5HO7JF2HQRFKMTUZ5HMGC56GVQRKX,
    MessagePill: 4HMQ4AYEDJT22I2YNFTDLCQCFDA4FZ3F, PageBreak: DZMYH5NNSYRJ4WDLWUBBLTQDLGTCANUI,
    Demo: 7OHCYYNDEID2BZ5AN5DDP7K4XXGJTRZB, ProgressBar.Determinate: J7HWVD2WBMZY7OCSOPNLPLHFQ4XCJBR2,
    ProgressBar.Indeterminate: KSULDKU4IPBMWPU7OQLLU4YN35XCYTSV}
  modules: {messaging: FHOPJKBWXXPKZKLDB7CJET3ZYPM3VVUZ, style: HH5PGMA7JQVLDPS5HWTF7IUGYMVKZQN5,
    popover: FS32WM35NQUXSJLRNDIUY2EDSTZYU2OW, session: I6CPANLB5O7M2VDR2CZKLBV7THBW2SJF,
    utils: HJ6S3PKHYTR3X7Q4KPXIRIPGOM2K3NQF, ProgressBar: 6RDMGEBZGTXV32KLZDKWPGBWXS3QKNRT,
    navigation: SZLQKNXZ652GPPZYTAO7SJEDSNHWJGNH, augment: 4FEE7FFSUFNUJ3UXME77V3LDGDN43OJN}
  server_modules: {authorisation: 6XYXFTWQENJAUYHVY3423GS4DWFK7T3R, server_utils: RDEDHUTEAHXBYAGYYT6X42MSCQCV6TVQ}
  assets: {loading-spinner.js: QZE2DBIZMXAJZXG3Q7L2Y3R7M2D4VG4N, standard-page.html: JYT2VG6NOSSLRNZR5GDSLLXUFJ7AZF4J,
    theme.css: S5NWY72JOUFUHCDRRQX7DV3C5CKF4TGN}
